# -*- coding: utf-8 -*-
"""PRODIGY_ML_01

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1V_jLqg0yg-9K9HTO-Y2QLwpb8teh1uNN
"""



import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

dataset = pd.read_csv('/content/pricing.csv')

dataset.head()

dataset.describe()

dataset.info()

dataset.dropna(inplace=True)

dataset.info()

dataset.columns

x = dataset[['Avg. Area Income', 'Avg. Area House Age', 'Avg. Area Number of Rooms',
       'Avg. Area Number of Bedrooms', 'Area Population']]
y = dataset['Price']

from sklearn.model_selection import train_test_split

x_train , x_test, y_train, y_test = train_test_split(x, y , test_size=0.6)

from sklearn.linear_model import LinearRegression

lr = LinearRegression()

lr.fit(x_train, y_train)

print(lr.intercept_)

coeff_ = pd.DataFrame(lr.coef_, x.columns,columns = ['Coefficients'])
coeff_

pred = lr.predict(x_test)

plt.scatter(y_test, pred)

from sklearn import metrics

print('MAE:', metrics.mean_absolute_error(y_test, pred))
print('MSE:', metrics.mean_squared_error(y_test, pred))
print('RMSE:', np.sqrt(metrics.mean_squared_error(y_test, pred)))