# -*- coding: utf-8 -*-
"""PRODIGY_ML_02

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18sOzHlygR0Jt2EN7EUdJRrYmdfguTemQ
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv('/content/Mall_Customers ml.csv')
df

df.head(3)

X=df.iloc[:,[3,4]].values

from sklearn.cluster import KMeans
wcss=[]
for i in range(1,11):
  #init for initialization
  kmeans=KMeans(n_clusters=i,init='k-means++',random_state=42)
  kmeans.fit(X)
  wcss.append(kmeans.inertia_)
plt.plot(range(1,11),wcss)

kmeans=KMeans(n_clusters=5,init='k-means++',random_state=42)
y_kmeans=kmeans.fit_predict(X)
print(y_kmeans)

plt.scatter(X[y_kmeans==0,0],X[y_kmeans==0,1],s=100,color='pink',label='Cluster1')
plt.scatter(X[y_kmeans==1,0],X[y_kmeans==1,1],s=100,color='blue',label='Cluster2')
plt.scatter(X[y_kmeans==2,0],X[y_kmeans==2,1],s=100,color='green',label='Cluster3')
plt.scatter(X[y_kmeans==3,0],X[y_kmeans==3,1],s=100,color='skyblue',label='Cluster4')
plt.scatter(X[y_kmeans==4,0],X[y_kmeans==4,1],s=100,color='yellow',label='Cluster5')

df.info()

df.describe()